# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api_dio.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'api_dio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapi_dio.proto\"Y\n\x10PicohaDioRequest\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.RequestType\x12\x0f\n\x07pin_num\x18\x02 \x01(\r\x12\x18\n\x05value\x18\x03 \x01(\x0e\x32\t.PinValue\"\x83\x01\n\x0fPicohaDioAnswer\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.AnswerType\x12\x1d\n\x05value\x18\x02 \x01(\x0e\x32\t.PinValueH\x00\x88\x01\x01\x12\x1a\n\rerror_message\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_valueB\x10\n\x0e_error_message*k\n\x0bRequestType\x12\x08\n\x04PING\x10\x00\x12\x15\n\x11SET_PIN_DIRECTION\x10\x01\x12\x11\n\rSET_PIN_VALUE\x10\x02\x12\x15\n\x11GET_PIN_DIRECTION\x10\x03\x12\x11\n\rGET_PIN_VALUE\x10\x04*4\n\x08PinValue\x12\x07\n\x03LOW\x10\x00\x12\x08\n\x04HIGH\x10\x01\x12\t\n\x05INPUT\x10\x02\x12\n\n\x06OUTPUT\x10\x03*&\n\nAnswerType\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_dio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTTYPE']._serialized_start=242
  _globals['_REQUESTTYPE']._serialized_end=349
  _globals['_PINVALUE']._serialized_start=351
  _globals['_PINVALUE']._serialized_end=403
  _globals['_ANSWERTYPE']._serialized_start=405
  _globals['_ANSWERTYPE']._serialized_end=443
  _globals['_PICOHADIOREQUEST']._serialized_start=17
  _globals['_PICOHADIOREQUEST']._serialized_end=106
  _globals['_PICOHADIOANSWER']._serialized_start=109
  _globals['_PICOHADIOANSWER']._serialized_end=240
# @@protoc_insertion_point(module_scope)
